<?php
declare(strict_types=1);

return [
    'not-allowed' => [
        '@codepo8',
        '10',
        '1960s',
        '-non_catalogati',
        '.evernote',
        '.login-as-a-service',
        '.n',
        '1',
        '10kbootcamp',
        '1707',
        '2011',
        '2016',
        '2017',
        '2017-01-28',
        '2020',
        '2022',
        '2read',
        '30',
        '12-factor',
        '351',
        '510',
        'aggregatedata',
        '697',
        'a',
        'already-read',
        'all-doomed',
        'admin',
        'aabill',
        'aiviq',
        'areterrible',
        'article',
        'articles',
        'themorningpaper',
        'anil-dash',
        'ifttt',
        'breakthrough_in_grey_room',
        'bs_jobs',
        'bullshit',
        'bullshit_job',
        'be_like_this',
        'bookmarks',
        'bookmarks_bar',
        'bookmarks_menu',
        'bruce',
        'bruce_schneier',
        '3wfav',
        'adversarial',
        'airplanes',
        'amazing',
        'amnesia',
        'announcement',
        'antipattern',
        'arc',
        'archive',
        'author'
        // A done
    ],
    'allowed'     => [
        'some-tag'      => ['any-tag'],
        'alt-right'     => ['#altright'],
        'new-atheism'   => ['#newatheism'],
        'politics'      => ['#politics'],
        'racism'        => ['#race&amp;amp;racism', '#race&amp;racism'],
        'religion'      => ['#religion'],
        'gender'        => ['#sexgender&amp;amp;feminism-related', '#sexgender&amp;feminism-related'],
        '2fa'           => ['2_factor_security'],
        'zero-trust'    => ['zerotrust'],
        'advertising'   => ['ads'],
        'aes'           => ['aes-gcm'],
        'airtags'       => ['airtag'],
        'algorithms'    => ['algorithm'],
        'love'          => ['amour'],
        'architecture'  => ['architektura'],
        'bayesian'      => ['@bayesian'],
        'issues'        => ['@issues'],
        'saas'          => ['@saas'],
        'open-source'   => ['open source', '@open_source'],
        'tutorials'     => ['@tutorial'],
        'best-practice' => ['best-practices', 'bestpractices', 'bestpractice'],
        'blockchain'    => ['blockchains'],
        'twitter'       => ['twitterlink'],
        'employment'    => ['job', 'jobs', 'work', 'antiwork'],
        'apps'          => ['app'],
        'ai'            => ['artificialintelligence'],

    ],
];