<?php

declare(strict_types=1);

return [
    'allowed' => [
        // #
        '2fa'                    => ['2_factor_security'],
        'meldkamer'              => ['112'],

        // A
        'alt-right'              => ['#altright'],
        'advertising'            => ['ads'],
        'aes'                    => ['aes-gcm'],
        'airtags'                => ['airtag'],
        'algorithms'             => ['algorithm'],
        'architecture'           => ['architektura'],
        'apps'                   => ['app'],
        'ai'                     => ['artificialintelligence', 'artificial-intelligence'],
        'activisme'              => [],
        'aivd'                   => [],
        'abuse'                  => [],
        'academia'               => [],
        'addiction'              => [],
        'adversarial'            => [],
        'advice'                 => [],
        'agile'                  => [],
        'airplanes'              => [],
        'alphabet'               => [],
        'amazon'                 => [],
        'android'                => [],
        'animals'                => [],
        'anonimiteit'            => [],
        'api'                    => ['apis'],
        'apple'                  => [],
        'appsec'                 => [],
        'art'                    => [],
        'assurance'              => [],
        'atheism'                => [],
        'atomic'                 => [],
        'attention'              => [],
        'audio'                  => [],
        'authentication'         => [],
        'automation'             => ['automatic'],
        'awareness'              => [],
        'aws'                    => [],
        'azure'                  => [],
        'agility'                => [],

        // B
        'backdoor'               => ['backdoors'],
        'backup'                 => ['backups'],
        'banking'                => ['banks', 'finance', 'betaalverkeer'],
        'bayesian'               => ['@bayesian', 'bayes'],
        'blockchain'             => ['blockchains', 'block'],
        'books'                  => ['book', 'boeken'],
        'bots'                   => ['bot', 'chatbot', 'chatbots'],
        'best-practice'          => ['best-practices', 'bestpractices', 'bestpractice'],
        'behavior'               => [],
        'bellingcat'             => [],
        'big-data'               => ['big data', 'bigdata'],
        'big-tech'               => ['big five', 'big-five', 'big tech'],
        'biometrics'             => [],
        'bitcoin'                => [],
        'blue-team'              => ['blue_team'],
        'bluetooth'              => [],
        'bodybuilding'           => [],
        'burnout'                => [],
        'business'               => ['business-technology', 'corporate', 'corporateincompetence', 'corporations'],
        'biology'                => [],
        'birds'                  => [],

        // C
        'cryptography'           => ['assymetric', 'cryptograph', 'multiparty computation', 'rsa', 'hashing', 'ciphertext','elliptic_curve_cryptography'],
        'capitalism'             => [],
        'carriere'               => ['career', 'carreer', 'career-advice'],
        'automotive'             => ['self-driving'],
        'centralised'            => ['centralization'],
        'children'               => [],
        'china'                  => [],
        'cia'                    => [],
        'civil-rights'           => ['civilrights'],
        'cli'                    => [],
        'climate-change'         => ['climatecrisis'],
        'cloud'                  => [],
        'code'                   => [],
        'cold-war'               => ['coldwar'],
        'comedy'                 => [],
        'communication'          => ['comms', 'communications'],
        'computer'               => [],
        'computer-science'       => ['computer_science', 'cs', 'compsci', 'computerscience', 'computing science'],
        'computer-security'      => ['computer_security'],
        'computers'              => ['computing'],
        'conspiracy'             => ['deep state'],
        'control'                => [],
        'controversy'            => [],
        'conversion'             => [],
        'corporate'              => [],
        'covid'                  => ['covid-19', 'covid19', 'corona'],
        'creativity'             => [],
        'crime'                  => [],
        'critical-thought'       => ['critical', 'critique', 'resist', 'criticisms'],
        'crowd'                  => [],
        'cryptanalysis'          => [],
        'crypto-currencies'      => ['cryptocurrencies', 'ethereum', 'crypto-currency', 'cryptocurrency', 'crypto', 'coins'],
        'cryptozoology'          => [],
        'csam'                   => [],
        'culture'                => [],
        'cyber'                  => [],
        'cyberattack'            => [],
        'cybercrime'             => [],
        'cybersecurity'          => [],
        'cyberwar'               => ['digitalwarfare'],
        'censure'                => [],
        'communities'            => [],
        'conference'             => ['rwc'],
        'cinema'                 => ['film', 'movies'],

        // D
        'data-mining'            => [],
        'databases'              => ['database'],
        'dating'                 => [],
        'ddos'                   => [],
        'decentralisation'       => ['decentralization', 'decentralized'],
        'decode'                 => [],
        'deep-learning'          => ['deep_learning', 'deeplearning'],
        'democracy'              => [],
        'design'                 => [],
        'development'            => ['developer', 'dev', 'appdev'],
        'deviance'               => [],
        'devops'                 => ['devop'],
        'devsecops'              => [],
        'dictionary'             => [],
        'differential-privacy'   => ['differential_privacy', 'differentialprivacy'],
        'digital'                => ['digitalization'],
        'docker'                 => [],
        'dutch'                  => [],
        'dystopia'               => [],
        'dkim'                   => [],
        'data'                   => ['data-driven'],
        'energy'                 => [],

        // E
        'employment'             => ['job', 'jobs', 'work', 'antiwork', 'werk'],
        'economics'              => ['economy'],
        'education'              => [],
        'eidas'                  => [],
        'elections'              => ['election', 'voting'],
        'email'                  => [],
        'encryption'             => [],
        'engineering'            => [],
        'espionage'              => ['spionage', 'cyberespionage', 'cyberspionage'],
        'ethics'                 => ['medical ethics'],
        'europe'                 => ['eu'],
        'exercise'               => [],
        'extremism'              => [],
        'ecc'                    => ['elliptic curves'],
        'euthanasia'             => [],

        // F
        'facebook'               => ['fb'],
        'fantasy'                => [],
        'fascism'                => [],
        'fbi'                    => [],
        'fiction'                => [],
        'fitness'                => ['workout'],
        'flickr'                 => [],
        'foaf'                   => [],
        'forensics'              => [],
        'fox-it'                 => [],
        'fraud'                  => [],
        'freedom'                => [],
        'functional-programming' => ['functionalprogramming'],
        'funny'                  => ['humour', 'humor', 'fun', 'satire', 'nerd-humor'],
        'future'                 => [],

        // G
        'gender'                 => ['#sexgender&amp;amp;feminism-related', '#sexgender&amp;feminism-related', 'gender studies'],
        'gchq'                   => [],
        'gdpr'                   => [],
        'git'                    => [],
        'github'                 => [],
        'gnu'                    => [],
        'gnupg'                  => ['gpg', 'openpgp', 'pgp'],
        'google'                 => [],
        'government'             => ['overheid'],
        'geopolitics'            => [],
        'germany'                => [],
        'gaming'                 => [],

        // H

        'hacking'                => ['hacker', 'hack', 'hackers'],
        'han'                    => [],
        'hardware'               => [],
        'health'                 => ['death'],
        'history'                => [],
        'home-automation'        => ['home_automation', 'homeassistant'],
        'homomorphic-encryption' => ['homomorphic encryption', 'homomorphic'],
        'humanity'               => ['humanities', 'humans'],

        // I
        'icloud'                 => [],
        'information-security'   => ['informationsecurity', 'information security', 'infosec'],
        'infrastructure'         => [],
        'intelligence'           => [],
        'internet'               => ['web'],
        'interview'              => ['interviews'],
        'investing'              => ['investment', 'invest', 'stock', 'stocks', 'beleggen'],
        'ios'                    => [],
        'iphone'                 => [],
        'israel'                 => [],
        'industry'               => [],

        // J
        // K
        'klokkenluiders'         => [],
        'knowledge-management'   => [
            'knowledgemanagment',
            'knowledge management',
            'knowledgemanagement',
            'knowledge',
            'tacit-knowledge',
            'thinking',
            'thought',
        ],
        'kpn'                    => [],

        // L
        'love'                   => ['amour'],
        'leadership'             => ['management'],
        'learning'               => ['learn', 'leer'],
        'leesvoer'               => [],
        'linux'                  => [],

        // M
        'machine-learning'       => ['machine_learning', 'machinelearning', 'ml'],
        'mathematics'            => ['math', 'maths'],
        'media'                  => [],
        'metoo'                  => [],
        'microsoft'              => [],
        'military'               => [],
        'mobile'                 => [],
        'money'                  => ['capital'],
        'multi-media'            => [],
        'music'                  => [],

        // N
        'nasa'                   => [],
        'nato'                   => [],
        'nederland'              => ['netherlands', 'nl'],
        'negotiation'            => [],
        'nft'                    => ['nfts'],
        'nist'                   => ['nist800', 'nist800-70'],
        'note-taking'            => ['notetaking'],
        'nsa'                    => [],
        'networking'             => [],


        // O
        'open-source'            => ['open source', '@open_source', 'opensource'],
        'oauth2'                 => ['oauth'],
        'ontology'               => [],
        'ontwikkeling'           => [],
        'osint'                  => [],
        'osx'                    => [],

        // P
        'productivity'           => ['lifehacks', 'lifehack', 'pomodoro', 'personal-productivity'],
        'politics'               => ['#politics', 'politiek'],
        'pki'                    => ['certificates', 'key-management', 'key-transparency', 'krypto_key_revocation', 'krypto_pki_ca', 'krypto_tls_cert', 'public-key'],
        'parenting'              => ['motherhood'],
        'psychology'             => [],
        'personal-finances'      => [],

        'palintir'                 => [],
        'patriarchy'               => [],
        'personal-branding'        => [],
        'personal-homepage'        => [],
        'personal-security'        => [],
        'philosophy'               => [],
        'photography'              => [],
        'politie'                  => ['police'],
        'privacy'                  => [],
        'programming'              => [],
        'physics'                  => [],
        'private'                  => [],
        'poems'                    => ['poezie', 'poetry'],

        // Q
        'quantum-cryptography'     => [
            'quantum',
            'post-quantum',
            'quantum cryptography',
            'post-quantum-cryptography',
            'pqc',
            'pqe',
            'post-quatum',
            'quantumcomputing',
        ],
        'quantum-key-distribution' => ['qkd'],

        // R
        'racism'                   => ['#race&amp;amp;racism', '#race&amp;racism', 'whitesupremacy'],
        'religion'                 => ['#religion'],
        'race'                     => [],
        'radio'                    => [],
        'red-teaming'              => ['red_teaming', 'redteam'],
        'russia'                   => [],
        'reading'                  => ['libraries', 'alternative_libraries', 'little_libraries', 'antilibrary', 'library'],
        'research'                 => [],


        // S
        'saas'                     => ['@saas'],
        'safety'                   => [],
        'science'                  => [],
        'sci-fi'                   => ['scifi'],
        'security'                 => [],
        'security-architecture'    => [],
        'self-hosted'              => ['selfhost'],
        'self-improvement'         => [
            'personal-improvement',
            'self_help',
            'selfhelp',
            'personal-development',
            'professional_development',
            'personal development',
        ],
        'sexism'                   => [],
        'signal'                   => [],
        'smart'                    => [],
        'snowden'                  => [],
        'social engineering'       => [],
        'social-media'             => ['social media', 'socialmedia', 'socialnetworking'],
        'social-sciences'          => ['social science', 'social-science'],
        'social-justice'           => ['social justice', 'sjw', 'socialjustice'],
        'solid'                    => [],
        'sollicitaties'            => [],
        'space'                    => [],
        'spotify'                  => [],
        'standards'                => ['standard'],
        'strategy'                 => [],
        'substack'                 => [],
        'supply-chain-security'    => ['supply-chain', 'supply chain security'],
        'surveillance'             => [],
        'sustainability'           => [],
        'switzerland'              => [],
        'signatures'               => [],
        'software'                 => ['softwareengineering'],
        'sociology'                => [],
        'sabsa'                    => [],
        'stress'                   => ['work-life'],


        // T
        'tutorials'                => ['@tutorial', '@tutorials'],
        'twitter'                  => ['twitterlink'],
        'teaching'                 => [],
        'technology'               => ['tech'],
        'terrorism'                => ['terrorist'],
        'teamwork'                 => ['team'],
        'thought'                  => [],
        'threat-modeling'          => ['threat-modelling', 'threat-model', 'threat modelling'],
        'time-management'          => ['time', 'time-tracking', 'time-confetti', 'prioritization'],
        'tls'                      => [],
        'tools'                    => ['tool'],
        'tor'                      => [],
        'trump'                    => [],
        'tumblr'                   => [],
        'tutorial'                 => [],
        'tv'                       => [],

        // U
        'usa'                      => ['america', 'united states'],
        'usability'                => [],

        // V
        'video'                    => [],
        'vulnerabilities'          => ['cve'],

        // W
        'web2.0'                   => [],
        'web3'                     => [],
        'webdevelopment'           => [],
        'werving'                  => ['recruiting', 'recruitment'],
        'whatsapp'                 => [],
        'windows'                  => [],
        'woke'                     => [],
        'women'                    => [],
        'women-in-tech'            => [],
        'wonen'                    => [],

        // Z
        'zero-trust'               => ['zerotrust'],
        'zero-knowledge'           => ['zkp', 'zeroknowledge', 'zeroknowledgeproofs'],
        'zorgplicht'               => [],
        'zuckerberg'               => [],
    ],
];
